# Generated by Django 5.0 on 2025-06-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_phone_numeber_permissions_users_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone_numeber',
            new_name='phone_number',
        ),
    ]
