# Generated by Django 5.0 on 2025-06-26 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_phone_numeber_users_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role_id',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.roles'),
        ),
    ]
