# Generated by Django 5.0 on 2025-06-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_users_role_id_users_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='roles',
        ),
    ]
