# Generated by Django 5.0 on 2025-06-26 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_name', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('student_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_name', models.CharField(blank=True, max_length=200, null=True)),
                ('section_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'student_detail',
            },
        ),
        migrations.CreateModel(
            name='teacherdetails',
            fields=[
                ('teacher_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_name', models.CharField(blank=True, max_length=200, null=True)),
                ('section_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'teacher_detail',
            },
        ),
    ]
