# Generated by Django 5.0 on 2025-06-27 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_id', models.CharField(blank=True, max_length=200, null=True)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_id', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_id', models.CharField(blank=True, max_length=200, null=True)),
                ('grade_name', models.CharField(blank=True, max_length=200, null=True)),
                ('section_id', models.CharField(blank=True, max_length=200, null=True)),
                ('section_name', models.CharField(blank=True, max_length=200, null=True)),
                ('attendance_status', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
